# fly.toml app configuration file generated for fast-zero-elias on 2024-09-15T14:13:01-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fast-zero-elias'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = "poetry run alembic upgrade head"

[[vm]]
  size = 'shared-cpu-1x'
