"""Add default value for updated_at cloumn

Revision ID: 3fcc9b7859ed
Revises: 57060fb59e51
Create Date: 2024-08-31 16:13:05.862557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcc9b7859ed'
down_revision: Union[str, None] = '57060fb59e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
